server.servlet.context-path=/stun
server.port=8087


# Configuração para Desenvolvimento (ex: BD Local)
main.datasource.jdbc-url=jdbc:mysql://localhost:3306/acs
main.datasource.username=root
main.datasource.password=root
main.datasource.maximum-pool-size=2

# Forçar log em INFO para ver o que acontece em Dev
logging.level.root=INFO
# Em desenvolvimento, queremos ver os logs do nosso código
level.com.github.freeacs=INFO